
# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://alfred-sun.github.io
shorthand_url: alfred-sun.github.io
title: Vermillion Phoinix by Alfred Sun
subtitle: Vermillion Phoinix
author:
  name: Alfred Sun
  nickname: dfbb
  email: sym_dfbb@163.com
  gmail: alfred.sunym@gmail.com
  schoolmail: alfred_sun@hust.edu.cn
  school: http://www.hust.edu.cn
  site: http://alfred-sun.github.io
simple_search: http://209.85.228.22/search # 61.19.1.110  # https://www.google.com/search
description: Simple personal blog for GitHub Pages

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "%a %e %b %Y, %l:%M %p"
# "%B %e, %Y at %H:%M %Z"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email: sym_dfbb@163.com

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root:
permalink: /blog/:year/:month/:day/:title/
source: .
destination: ./_site
plugins: ./_plugins
code_dir: downloads/code/
category_dir: blog/category/
tag_dir: blog/tag/
archive_dir: blog/archive/
asset_dir:
  images: assets/images
  fonts: assets/fonts
  stylesheets: assets/stylesheets
  javascripts: assets/javascripts

safe: false
encoding: "utf-8"
# baseurl: "/old"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "Alfred Sun"

# Conversion
# enable github favored Markdown
markdown: redcarpet  # rdiscount
# rdiscount:
redcarpet:
  extensions:
    - fenced_code_blocks
    - highlight
    - tables
    - strikethrough
    - autolink
    - footnotes
    - smart
highlighter: pygments # Jekyll's default python pygments have been replaced by pygments.rb
# pygments: true

lsi: false				# Produce an index for related posts or not
paginate:  7			# Posts per page on the blog index
paginate_path: "blog/page/:num"  # Directory base for pagination URLs eg. /posts/2/
recent_posts: 10       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [
    asides/recent_posts.html,
    custom/asides/category_list.html
]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
blog_index_asides: [
    custom/asides/what_is_octostrap3.html,
    asides/recent_posts.html,
    custom/asides/category_list.html,
    asides/github.html
]
# post_asides:
# page_asides:

# ----------------------- #
#   Blog Media Directory   #
# ----------------------- #
picture_dir: /media/pictures
video_dir: /media/videos
music_dir: /media/music
document_dir: /media/documents
demo_dir: /media/demo

# Enable automatic sitemap generation
# GitHub Pages will not override a sitemap.xml file that exists in the root of your repository.
# https://help.github.com/articles/sitemaps-for-github-pages/
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: Alfred Sun
github_repo_count: 4
github_show_profile_link: true
github_skip_forks: true
github_site: http://github.com/Alfred-Sun

# SNS
weibo_site: http://weibo.com/symdfbb
baidu_site: http://hi.baidu.com/symdfbb
byhh_site: http://bbs.whnet.edu.cn
qq_site: http://user.qzone.qq.com/914738897

# Twitter
twitter_user:
twitter_tweet_button: true

# Google +1
google_plus_one: true
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: alfredsun
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id:
baidu_statistics_tracking_id: a8e39b00a0e3f52df3e0deea5d0a691b
cnzz_statistics_tracking_id: 1253608568

# Facebook Like
facebook_like: true

